import { SceneDoc } from './doc'

/**
 * A starter document so the editor opens with something to manipulate.
 * Later, templates come from Supabase — each is just a SceneDoc with
 * is_template = true. "Use template" duplicates it into the user's projects.
 */
export function starterTemplate(): SceneDoc {
  return {
    id: 'starter',
    name: 'Sale — 30% Off',
    width: 1080,
    height: 1920,
    fps: 30,
    durationInFrames: 150,
    background: '#ffe14d',
    layers: [
      {
        id: 'bg-shape',
        name: 'Backdrop',
        type: 'shape',
        x: 90,
        y: 250,
        width: 900,
        height: 1100,
        rotation: -4,
        opacity: 1,
        startFrame: 0,
        endFrame: 150,
        shape: 'rect',
        fill: '#ff5b7f',
        radius: 48,
      },
      {
        id: 'photo',
        name: 'Product photo',
        type: 'image',
        x: 240,
        y: 560,
        width: 600,
        height: 600,
        rotation: 0,
        opacity: 1,
        startFrame: 0,
        endFrame: 150,
        src: 'https://picsum.photos/seed/silkproduct/800/800',
        fit: 'cover',
        radius: 24,
      },
      {
        id: 'headline',
        name: 'Headline',
        type: 'text',
        x: 140,
        y: 300,
        width: 800,
        height: 220,
        rotation: 0,
        opacity: 1,
        startFrame: 0,
        endFrame: 150,
        text: '30% OFF',
        fontSize: 180,
        fontWeight: 900,
        color: '#101015',
        align: 'center',
        lineHeight: 1,
        fontFamily: 'Inter, sans-serif',
      },
      {
        id: 'sub',
        name: 'Subhead',
        type: 'text',
        x: 140,
        y: 1240,
        width: 800,
        height: 120,
        rotation: 0,
        opacity: 1,
        startFrame: 0,
        endFrame: 150,
        text: 'Sitewide sale · use code SILK',
        fontSize: 46,
        fontWeight: 600,
        color: '#ffffff',
        align: 'center',
        lineHeight: 1.2,
        fontFamily: 'Inter, sans-serif',
      },
    ],
  }
}
